config/routes.rb
Rails.application.routes.draw do
	  resources :people
	  devise_for :users

	resources :jobs


	  root 'jobs#index'

	 devise_scope :user do
	  get 'login', to: 'devise/sessions#new'
	  get 'signup', to: 'devise/registrations#new'
	  delete 'logout', to: 'devise/sessions#destroy'
	end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/job.rb
class Job < ApplicationRecord
	belongs_to :user

  has_attached_file :job_img, styles: { medium: "300x300>", job_show: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :job_img, content_type: /\Aimage\/.*\z/

  def self.search(search)
		if search
			where(["title LIKE ?","%#{search}%"])
		else
			all
		end
		
	end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:show, :index]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all.paginate(:page => params[:page], :per_page => 7).search(params[:search]).order('created_at DESC')
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = current_user.jobs.build
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = current_user.jobs.build(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy = Job.find(params[:id])
    @job.destroy
 
    redirect_to articles_path

    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:job_img, :title, :description, :location, :job_benefits, :job_task, :job_link, :job_salary, :job_type)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_details.html.erb
     <!-- wrapper page -->
    <div class="wrapper">

      <!-- main-header -->
      <header class="main-header">


        <!-- main navbar -->
        <nav class="navbar navbar-default main-navbar hidden-sm hidden-xs">
          <div class="container">
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <a  href="/"><img style="padding: 6px;" class="navbar-brand" src="https://res.cloudinary.com/dko7n7x16/image/upload/v1524770564/LogoMakr_4hyY2t_iguecr.png"></a>

                    
              <ul class="nav navbar-nav navbar-right">
                <li class="link-btn"><a href="/users/sign_in"><span class="btn btn-theme  btn-pill btn-xs btn-line">Post job</span></a></li>
              </ul>
            </div>
          </div>
        </nav><!-- end main navbar -->

        <!-- mobile navbar -->
        <div class="container">
          <nav class="mobile-nav hidden-md hidden-lg">
            <a href="#" class="btn-nav-toogle first">
              Post a Job</a>
            
          </nav>
        </div><!-- mobile navbar -->


        <!-- form search area-->
        <div class="container">
          <div class="row">

            

            <div class="col-md-12">
              <!-- form search -->
              <form class="form-search-list" accept-charset="UTF-8" role="search" action="/jobs" method="get">
                <div class="row">
                  <div class="col-md-10">
                    <div class="form-group">
                      <label class="color-white">Search Job</label>
                      <input name="utf8" type="hidden" value="&#x2713;" />
                      <input type="text" name="search" id="search" class="form-control" placeholder="Technical Assistant" >
                    </div>
                  </div>
                  
                  <div class="col-md-2">
                    <div class="form-group">
                      <label class="hidden-xs">&nbsp;</label>
                      <button class="btn btn-block btn-theme  btn-success">Search</button>
                    </div>
                  </div>
                </div>
              </form>  <!-- form search -->
            </div>


          </div>


          

        </div><!-- end form search area-->

      </header><!-- end main-header -->

app/views/jobs/_footer.html.erb
<!-- main-footer -->
      <footer class="main-footer">


        <div class="container">
          <div class="row">
            <div class="col-sm-6">
              <ul class="list-inline link-footer text-center-xs">
                <li><a href="">Home</a></li>
                <li><a href="">Blog</a></li>
                <li><a href="">About Us</a></li>
                <li><a href="">Contact Us</a></li>
              </ul>
            </div>
            <div class="col-sm-6 ">
              <p class="text-center-xs hidden-lg hidden-md hidden-sm">Stay Connect</p>
              <div class="socials text-right text-center-xs">
                <a href="#"><i class="fa fa-facebook"></i></a>
                <a href="#"><i class="fa fa-twitter"></i></a>
                <a href="#"><i class="fa fa-youtube-play"></i></a>
                <a href="#"><i class="fa fa-linkedin"></i></a>
              </div>
            </div>
          </div>
        </div>
      </footer><!-- end main-footer -->

    </div><!-- end wrapper page -->

app/views/jobs/_form.html.erb
                <%= form_with(model: job, local: true) do |form| %>
                
                
                </div>
                <div class="col-md-8 col-md-offset-2">
                <div class="modal-body">
                  <div class="form-group">
                    <label>Upload Logo</label>
                    <%= form.file_field :job_img, id: :job_img, :class => 'form-control' %>
                  </div>
                  <div class="form-group">
                    <label>Job Title</label>
                    <%= form.text_field :title, id: :job_title, :class => 'form-control', :placeholder => 'Technical Consultant', :style => "text-transform: capitalize" %>
                  </div>
                  
                  <div class="form-group">
                    <label>Job Description</label>
                    <%= form.text_area :description, id: :job_description, :class => 'form-control', :row => '6', :placeholder => 'PHP and/or Java. Architect features with the development team. Krossover is looking for a Web Application Developer to join our team of smart developers' %>
                  </div>

                  <div class="form-group">
                    <label>Location</label>
                    <%= form.text_field :location, id: :job_location, :class => 'form-control' %>
                  </div>

                  <div class="form-group">
                    <label>Company</label>
                    <%= form.text_field :company, id: :job_company, :class => 'form-control' %>
                  </div>

                  <div class="form-group">
                    <label>Job Benefits</label>
                    <%= form.text_area :job_benefits, id: :job_job_benefits, :class => 'form-control', :row => '6', :placeholder => '404 Health Plan' %>
                  </div>

                   <div class="form-group">
                    <label>Responsibilities</label>
                    <%= form.text_area :job_task, id: :job_job_task, :class => 'form-control' %>
                  </div>

                   <div class="form-group">
                    <label>Application Link</label>
                    <%= form.text_field :job_link, id: :job_job_link, :class => 'form-control' %>
                  </div>

                  <div class="form-group">
                    <label>Job Salary</label>
                    <%= form.text_field :job_salary, id: :job_job_salary, :class => 'form-control' %>
                  </div>

                  <div class="form-group">
                    <label>Job Type</label>
                    <%= form.text_field :job_type, id: :job_job_type, :class => 'form-control' %>
                  </div>

                  <div class="checkbox flat-checkbox">
                    <label>
                      <input type="checkbox"> 
                      <span class="fa fa-check"></span>
                      Send a copy to my email address?
                    </label>
                  </div>
                </div>
                  
                      <div class="modal-footer">
                      <%= link_to 'Back', jobs_path, :class => 'btn btn-default btn-theme' %>
                      <%= form.submit 'Submit', :class => 'btn btn-success btn-theme' %>
                    </div>
                  
                    
              <% end %>
</div>

app/views/jobs/_nav.html.erb
<div class="wrapper">
      <!-- main-header -->
      <header class="main-header" >


        <!-- main navbar -->
        <nav class="navbar navbar-default main-navbar hidden-sm hidden-xs">
          <div class="container">
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <a  href="#"><img style="padding: 6px;" class="navbar-brand" src="https://res.cloudinary.com/dko7n7x16/image/upload/v1524770564/LogoMakr_4hyY2t_iguecr.png"></a>

                   
              <ul class="nav navbar-nav navbar-right">
                <li class="link-btn"><a href="/login"><span class="btn btn-theme  btn-pill btn-xs btn-line">Post job</span></a></li>
              </ul>
            </div>
          </div>
        </nav><!-- end main navbar -->

        <!-- mobile navbar -->
        <div class="container">
          <nav class="mobile-nav hidden-md hidden-lg">
            <a href="/jobs/new" class="btn-nav-toogle first">
              Post a Job</a>
            
          </nav>
        </div><!-- mobile navbar -->

        <div class="hero-header" style="background: url(https://res.cloudinary.com/dko7n7x16/image/upload/v1524766483/space-desk-workspace-coworking_eearbt.jpg); min-height: 385px;">
          <div class="inner-hero-header" style="bottom: inherit;">
            <div class="container">
              <div class="text-center logo"> <a href="index.html"><img src="assets/theme/images/logo.png" alt=""></a></div>
              <div class="relative">
                <i class="fa fa-globe ic-fade-globe"></i>
                <!-- form search -->
                <form style="max-width: inherit; background: inherit;" class="form-search-home" accept-charset="UTF-8" role="search" action="/jobs" method="get">
                  <div class="row">
                    <div class="col-md-12">
                      <div class="form-group">
                        <h3 style="color: #fff;">Find a Job By Title</h3>
                        <input name="utf8" type="hidden" value="&#x2713;" />
                        <input class="form-control  input-lg" placeholder="Business developer" name="search" id="search">
                      </div>
                    </div>
                    
                  </div>
                  
                  
                </form> <!-- end form search -->
              </div>
            </div>
          </div>

        </div>
      </header><!-- end main-header -->

    </div> 

app/views/jobs/edit.html.erb
<%= render 'form', job: @job %>

app/views/jobs/index.html.erb
      <!-- body-content -->
      <div class="body-content clearfix" >

        <div class="bg-color2">
          <div class="container">
            <div class="row">
              <div style="" class="col-md-6 col-md-offset-3">

                <!-- box listing -->
                <div class="block-section-sm box-list-area">
                  
                  <!-- desc top -->
                  <div class="row hidden-xs">
                    <div class="col-sm-6  ">
                      <p><strong class="color-black">Latest jobs in Nigeria</strong></p>
                    </div>
                    <div class="col-sm-6">
                      <p class="text-right">
                        Jobs 1 to 10 of 578
                      </p>
                    </div>
                  </div><!-- end desc top -->
                  <% @jobs.each do |job| %>
                  <!-- item list -->  
                  <div class="box-list">
                    <div class="item">
                      <div class="row">
                        <div class="col-md-1 hidden-sm hidden-xs"><div class="img-item"><%= image_tag job.job_img.url(:job_show) %></div></div>
                        <div class="col-md-11">
                          <h3 class="no-margin-top"><a href="/jobs/<%= job.id %>" class=""><%= job.title %> <i class="fa fa-link color-white-mute font-1x"></i></a></h3>
                          <h5><span class="color-black">CollegeHumor</span> - <span class="color-white-mute"><%= job.location %></span></h5>
                          <p class="text-truncate ">Back development experience in PHP 5, and a strong understanding of Object Oriented Programming within an MVC framework</p>
                          <div>
                            <span class="color-white-mute">16 hours ago</span> - 
                                
                                
                              <a href="/jobs/<%= job.id %>" class="btn btn-theme btn-xs btn-default">Apply</a>
                            
                          </div>
                        </div>
                      </div>
                    </div><!-- end item list -->
                    
                    <!-- item list -->
                  <% end -%>  

                  </div>


                  

                  <!-- pagination -->
                  <nav >
                    <ul class="pagination pagination-theme  no-margin">
                      <%= will_paginate @jobs %>
                      </li>
                    </ul>
                  </nav><!-- pagination -->

                </div><!-- end box listing -->


              </div>
              
            </div>
          </div>
        </div>
        <!-- modal need login -->
        <div class="modal fade" id="need-login">
          <div class="modal-dialog modal-md">
            <div class="modal-content">

              <div class="modal-header text-center">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" >You must login to save jobs</h4>
              </div>
              <div class="modal-footer text-center">
                <a href="#" class="btn btn-default btn-theme" >Login</a>
                <a href="#" class="btn btn-success btn-theme">Create account (it's free)</a>
              </div>

            </div>
          </div>
        </div><!-- end modal  need login -->


        <!-- modal need login -->
        <div class="modal fade" id="modal-email">
          <div class="modal-dialog modal-md">
            <div class="modal-content">
              <form>
                <div class="modal-header ">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <h4 class="modal-title" >Send this job to yourself or a friend:</h4>
                </div>
                <div class="modal-body">
                  <div class="form-group">
                    <label>From my email address</label>
                    <input type="email" class="form-control "  placeholder="Enter Email">
                  </div>
                  <div class="form-group">
                    <label>To email address</label>
                    <input type="email" class="form-control "  placeholder="Enter Email">
                  </div>

                  <div class="form-group">
                    <label>Comment (optional)</label>
                    <textarea class="form-control" rows="6" placeholder="Something Comment"></textarea>
                  </div>
                  <div class="checkbox flat-checkbox">
                    <label>
                      <input type="checkbox"> 
                      <span class="fa fa-check"></span>
                      Send a copy to my email address?
                    </label>
                  </div>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default btn-theme" data-dismiss="modal">Close</button>
                  <button type="submit" class="btn btn-success btn-theme">Send</button>
                </div>
              </form>
            </div>
          </div>
        </div><!-- end modal  need login -->        
      </div><!--end body-content -->
    <%= render 'footer' %>

app/views/jobs/new.html.erb
<div class="container">
	
<div class="row">
  <div class="
">
    <%= render 'form', job: @job %>

  </div>
</div>

</div>
<%= render 'footer' %>

app/views/jobs/show.html.erb
<div class="body-content clearfix">

    <div class="bg-color2">
        <div class="container">
            <div class="row">
                <div class="col-md-9">

                    <!-- box listing  -->
                    <div class="block-section-sm box-list-area">

                        <!-- top desc -->
                        <div class="row hidden-xs">
                            <div class="col-sm-6 ">
                                <h4><strong class="color-black"><%= @job.title %></strong></h4>
                            </div>
                            
                        </div>
                        <!-- end top desc -->

                        <!-- listing -->
                        <div class="box-list">

                            <!-- item listing  -->
                            <div class="item">
                                <div class="row">

                                    <div class="col-md-11">


                                        <p>
                                            Lumos offers clean and affordable solar power to a market of 1.3 billion potential customers who live off the electricity grid.Lumos enables people to replace hazardous and expensive kerosene generators and lanterns with modern solar electricity that
                                            can power lights, cellphones, fans, computers, TVs and other small electronic devices (all at once, every day). By offering Solar Power as a Service, Lumos offers homes and small businesses a simple and affordable
                                            way to pay for electricity in small installments using their mobile phones</p><br>

                                        <h4 class="no-margin-top"><a href="resume_details.html" class="">Job Desription</a></h4>
                                        <p>
                                            <%= @job.description %></p><br>
                                        <h4 class="no-margin-top"><a href="resume_details.html" class="">Job Responsibilities</a></h4>
                                        <p>
                                            <%= @job.job_task %></p><br>
                                        <h4 class="no-margin-top"><a href="resume_details.html" class="">Job Benefits</a></h4>
                                        <p>
                                            <%= @job.job_benefits %></p><br><br>
                                        <div>
                                            <a href="<%= @job.job_link %>" target="_blank" class="btn btn-xs-bg btn-theme btn-success">Apply for this job</a>
                                            <% if user_signed_in? %>
                                                <% if @job.user_id == current_user.id %>
                                                <%= link_to 'Edit this job', edit_job_path(@job), :class => 'btn btn-xs-bg btn-theme btn-default' %>
                                                <%= link_to 'Delete', job_path(@job), :class => 'btn btn-xs-bg btn-theme btn-danger',
                                                    method: :delete,
                                                    data: { confirm: 'Are you sure?' } %>
                                                <% end %>
                                            <% end %>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- end item listing  -->



                        </div>
                        <!-- end  listing -->



                        <!-- pagination -->

                        <!-- pagination -->

                    </div>
                    <!-- end  box listing  -->


                </div>
                <div class="col-md-3">
                    <div class="block-section-sm side-right">

                        <!-- filter   -->
                        <div class="row">

                            <div class="col-xs-6" style="width: inherit;">
                                <p class="text-right">
                                    <strong>Deadline</strong> - <a href="#" class="link-black"><strong>14-July-2019</strong></a>
                                </p>
                            </div>
                        </div>


                        <!-- filter   -->
                        <div class="box-list">

                            <!-- item listing  -->
                            <div class="item">
                                <div class="row">

                                    <div class="col-md-12">
                                        <h3 class="no-margin-top"><a href="resume_details.html" class="">Job Summary</a></h3>

                                        <h5><span class="color-black">Company</span></h5>
                                        <p>Isixty Visuals Nig Ltd</p>
                                        <h5><span class="color-black">Job Level

</span></h5>
                                        <p>Experienced (Non-Manager)</p>
                                        <h5><span class="color-black">Location

</span></h5>
                                        <p><%= @job.location %> <span class="color-white-mute"></span> </p>
                                        <h5><span class="color-black">Specialization

</span></h5>
                                        <p>Customer Service </p>
                                        <h5><span class="color-black">Job Type

</span></h5>
                                        <p><%= @job.job_type %> </p>
                                        <h5><span class="color-black">Minimum Qualification

</span></h5>
                                        <p>Degree </p>
                                        <h5><span class="color-black">Years of Experience

</span></h5>
                                        <p>1 -3 Years </p>
                                        <h5><span class="color-black">Salary

</span></h5>
                                        <p>₦<%= @job.job_salary %></p>
                                        <h5><span class="color-black">Application Deadline

</span></h5>
                                        <p>4th-July-2025</p>
                                        <div>
                                            <a href="<%= @job.job_link %>" target="_blank" class="btn btn-xs-bg btn-theme btn-success">Apply Here</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- end item listing  -->



                        </div>
                        <!-- end filter   -->
                    </div>


                </div>
            </div>
        </div>
    </div>


    
</div>
<!-- main-footer -->
<%= render 'footer' %>
    <!-- end wrapper page -->